import type { Metadata } from "next";
import Link from "next/link";

import { PageTransition } from "@/components/ui/page-transition";
import { getDiscordAppealUrl } from "@/lib/env";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Atlas Privacy Policy covering data collection, use, sharing, retention, and user rights.",
};

const EFFECTIVE_DATE = "February 14, 2026";

export default function PrivacyPage() {
  const supportUrl = getDiscordAppealUrl();

  return (
    <PageTransition className="mx-auto min-h-screen w-full max-w-[980px] px-4 py-10 sm:px-6 lg:px-8">
      <header className="mb-8 flex flex-wrap items-center justify-between gap-3">
        <Link
          href="/"
          className="rounded-lg px-3 py-1.5 text-sm text-[#b9b0a2] transition hover:bg-white/6 hover:text-white"
        >
          Back Home
        </Link>
        <div className="flex items-center gap-2">
          <Link href="/tos" className="btn btn-secondary text-sm">
            Terms
          </Link>
          <Link href="/docs" className="btn btn-secondary text-sm">
            Docs
          </Link>
        </div>
      </header>

      <section className="panel space-y-4 p-7">
        <p className="section-kicker">Legal</p>
        <h1 className="text-3xl font-semibold tracking-tight text-white">Privacy Policy</h1>
        <p className="text-xs uppercase tracking-[0.12em] text-[#8f8679]">Effective date: {EFFECTIVE_DATE}</p>
        <p className="text-sm leading-relaxed text-[#c2b9ac]">
          This policy explains what data Atlas collects, why it is used, when it is shared, and what control you have
          over your information.
        </p>
      </section>

      <section className="panel mt-6 space-y-4 p-7 text-sm leading-relaxed text-[#c2b9ac]">
        <h2 className="text-xl font-semibold text-white">1. Scope</h2>
        <p>
          This Privacy Policy applies to the Atlas website, editor, public profile pages, and related services
          (collectively, the &quot;Service&quot;). By creating an account or using Atlas, you agree to this policy.
        </p>

        <h2 className="text-xl font-semibold text-white">2. Information we collect</h2>
        <p>We collect information you provide directly, information generated by usage, and limited technical data.</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Account data: email address, account identifier, login method, and authentication metadata.</li>
          <li>Profile data: handle, display name, bio, links, badges, widgets, cursor settings, and appearance settings.</li>
          <li>Uploaded content: avatar files, link icons, profile background media, and custom fonts.</li>
          <li>Usage data: profile views, link clicks, editor interaction events, save timestamps, and error logs.</li>
          <li>Integration data: optional Discord connection identifiers and related profile presence metadata.</li>
          <li>Device/network data: IP address, browser type, operating system, and approximate region derived from IP.</li>
        </ul>

        <h2 className="text-xl font-semibold text-white">3. How we use information</h2>
        <ul className="list-disc space-y-2 pl-5">
          <li>Provide authentication, account access, profile publishing, and editor functionality.</li>
          <li>Operate analytics (views/clicks) and show performance information in dashboard features.</li>
          <li>Enforce product rules including privacy settings, moderation actions, and premium feature gating.</li>
          <li>Prevent abuse, secure the platform, investigate incidents, and enforce legal terms.</li>
          <li>Improve reliability and product quality through diagnostics and service monitoring.</li>
        </ul>

        <h2 className="text-xl font-semibold text-white">4. AI feature processing</h2>
        <p>
          If you use AI Assist features, request content (for example bio prompts or link context) is sent to an AI
          provider to generate suggestions. AI output is generated on request and should be reviewed before publishing.
          Do not submit sensitive personal information into AI prompts.
        </p>

        <h2 className="text-xl font-semibold text-white">5. Cookies and local storage</h2>
        <p>
          Atlas and its providers may use cookies, session storage, and similar technologies for authentication,
          security, preferences, and essential performance telemetry.
        </p>

        <h2 className="text-xl font-semibold text-white">6. How information is shared</h2>
        <p>Atlas does not sell personal information. Information may be shared only in the following situations:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>With infrastructure providers that host authentication, database, storage, and optional AI services.</li>
          <li>When you choose to publish content publicly, including your profile page and any public links/media.</li>
          <li>When required by law, legal process, or to protect the safety, rights, and security of Atlas or others.</li>
          <li>As part of a merger, acquisition, or asset transfer, subject to standard confidentiality protections.</li>
        </ul>

        <h2 className="text-xl font-semibold text-white">7. Retention</h2>
        <p>
          We retain account and profile data while your account remains active. Data may be retained for a limited
          period afterward for legal obligations, fraud prevention, dispute resolution, and operational backups.
        </p>

        <h2 className="text-xl font-semibold text-white">8. Your controls and rights</h2>
        <ul className="list-disc space-y-2 pl-5">
          <li>Edit profile content and settings directly in the editor.</li>
          <li>Set your profile to private to disable public access.</li>
          <li>Request account-related support through the Atlas support channel.</li>
          <li>Where applicable by law, request access, correction, export, or deletion of personal data.</li>
        </ul>

        <h2 className="text-xl font-semibold text-white">9. Security</h2>
        <p>
          Atlas uses administrative, technical, and organizational safeguards designed to protect personal information.
          No system is fully secure, and users remain responsible for maintaining strong account credentials.
        </p>

        <h2 className="text-xl font-semibold text-white">10. Children</h2>
        <p>
          Atlas is not directed to children under 13 (or higher minimum age where required by local law). If you
          believe a child provided personal information, contact support so data can be reviewed and removed.
        </p>

        <h2 className="text-xl font-semibold text-white">11. International data handling</h2>
        <p>
          Atlas and service providers may process data in countries other than your own. By using the Service, you
          consent to cross-border transfer and processing as needed to operate Atlas.
        </p>

        <h2 className="text-xl font-semibold text-white">12. Policy updates</h2>
        <p>
          This policy may change over time. If material changes are made, we will update the effective date on this
          page. Continuing to use Atlas after changes take effect means you accept the updated policy.
        </p>

        <h2 className="text-xl font-semibold text-white">13. Contact</h2>
        <p>
          For privacy questions, data requests, or account issues, use Discord support:{" "}
          <Link href={supportUrl} target="_blank" rel="noreferrer" className="text-[#cbb89a] underline">
            open support
          </Link>
          .
        </p>
      </section>
    </PageTransition>
  );
}
